### ISSUE TITLE
Does it support cbz?

### ISSUE THREAD

**Issue by ghost** [rehhouari/clovre#1]
Also does it have auto tracking with anilist if so does it track reading by chapter name or?

**Comment by rehhouari** [comment]
no sorry it have neither and i don't think im going to implement them (not yet atleast since im working on something else currently)
for cbz, im using a new feature in browsers to open a folder and read its content easily, adding cbz support would require using a library that extract these files in the browser then read the content and it seems a little bit of work.
There seems to be one already doing that you might like: https://github.com/afzafri/Web-Comic-Reader

and for auto tracking, getting a number from the chapter name is easy, but there are cases where the folder is named like: Vol 2. Chapter 10. doing tests for all the different cases doesn't seem to be worth it. and forcing only one naming standard would make this not support a lot of managa downloaders cause they use different naming conventions
